import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { Lightning, BatteryCharging, BatteryHigh, GearSix, Heart, WifiHigh, AppleLogo, Sun, Moon, CircleHalf, Check, ArrowUpRight, CaretRight, X, ChartLine, DownloadSimple, Info, Clock, SlidersHorizontal, WarningCircle, CheckCircle, Database, Bell, ShieldCheck, Trash, ArrowClockwise, Desktop } from '@phosphor-icons/react';
import { PowerFlow } from './PowerFlow';
import { PowerChart } from './PowerChart';
import { normalizeAppearance, resolveAppearance, scenarios, watt, makeHistory, historyCsv } from './model';

const appearanceKey = 'macpower.appearance.v1';
const themeLabels = { system: '跟随系统', light: '浅色', dark: '深色' };
const metrics = { battery: '电池净功率', input: '电源输入', system: '整机耗电', percent: '电池电量' };
const seriesNames = { input: '电源输入', system: '整机耗电', battery: '电池净功率' };
function loadTheme() { try { return normalizeAppearance(localStorage.getItem(appearanceKey)); } catch { return 'system'; } }
function loadPreferences() { try { const p = JSON.parse(localStorage.getItem('macpower.preferences.v1') || '{}'); return { metric: metrics[p.metric] ? p.metric : 'battery', extra: !!p.extra, record: p.record !== false, retention: [7,30,90].includes(p.retention) ? p.retention : 7, low: !!p.low, charged: !!p.charged }; } catch { return { metric: 'battery', extra: false, record: true, retention: 7, low: false, charged: false }; } }
function Logo() { return <span className="app-logo"><Lightning size={23} weight="fill" /></span>; }
function IconButton({ label, onClick, children }) { return <button className="icon-button" title={label} aria-label={label} onClick={onClick}>{children}</button>; }
function Toggle({ label, description, checked, onChange }) { return <label className="setting-row"><span><span className="setting-label">{label}</span><span className="setting-description">{description}</span></span><input type="checkbox" role="switch" aria-label={label} checked={checked} onChange={e => onChange(e.target.checked)} /></label>; }
function Modal({ title, kind = '', children, onClose }) { const ref = useRef(null); useEffect(() => { const d = ref.current; d.showModal(); return () => d.close(); }, []); return <dialog ref={ref} className={`modal ${kind}`} aria-label={title} onCancel={onClose}><div className="modal-header"><h2>{title}</h2><IconButton label="关闭窗口" onClick={onClose}><X size={19} /></IconButton></div>{children}</dialog>; }

function Trends({ rows, theme, scenario, period, setPeriod, series, setSeries, point, setPoint, available, onExport, onExpand, expanded = false }) {
  const values = rows.map(r => r.battery).filter(v => v != null);
  const average = values.length ? values.reduce((a,b) => a+b,0)/values.length : null;
  const peak = values.length ? values.reduce((a,b) => Math.abs(b)>Math.abs(a)?b:a,0) : null;
  return <section className={`trends-view ${expanded ? 'expanded' : ''}`} aria-label="功率趋势"><div className="section-title"><div><h2>功率趋势</h2><p>看清每一瓦，随时间的变化。</p></div><IconButton label="导出当前示例数据" onClick={onExport}><DownloadSimple size={19} /></IconButton></div><div className="period-control" role="group" aria-label="趋势时段">{[[15,'15 分钟'],[60,'1 小时'],[1440,'24 小时']].map(([n,label]) => <button key={n} aria-pressed={period===n} onClick={() => setPeriod(n)}>{label}</button>)}</div>{available && !scenario.stale ? <><div className="trend-units"><span>功率 / W</span><span>示例曲线</span></div><PowerChart rows={rows} theme={theme} series={series} onPoint={setPoint} /><div className="chart-legend">{Object.entries(seriesNames).map(([key,label]) => <button key={key} aria-pressed={series.includes(key)} className={series.includes(key)?'':'muted'} onClick={() => setSeries(current => current.includes(key)?current.length===1?current:current.filter(k=>k!==key):[...current,key])}><span className={`legend-mark ${key}`} />{label}</button>)}</div><div className="point-readout"><time>{(point||rows.at(-1)).label}</time>{series.map(key => <span key={key}>{seriesNames[key]} <strong>{watt((point||rows.at(-1))[key],key==='battery')} W</strong></span>)}</div><div className="trend-summary"><div><span>平均电池功率</span><strong>{watt(average,true)} <small>W</small></strong></div><div><span>峰值电池功率</span><strong>{watt(peak,true)} <small>W</small></strong></div></div><p className="section-note">{period===1440?'9 月 22 日 19:42 — 9 月 23 日 19:42':'2026 年 9 月 23 日'} · 示例时间区间</p><div className="event-row"><Clock size={17}/><div><strong>{scenario.name}</strong><span>本段为同一供电状态的演示数据</span></div></div></>:<div className="empty-state"><ChartLine size={35}/><h3>{scenario.stale?'等待新的有效读数':'还没有可用的历史记录'}</h3><p>{scenario.stale?'过期数据不会被绘制成当前功率。':'开始记录后，功率变化会显示在这里。'}</p></div>}{!expanded&&<button className="text-action full-trend" onClick={onExpand}>打开完整趋势 <ArrowUpRight size={16}/></button>}</section>;
}

export function App() {
  const [appearance,setAppearance]=useState(loadTheme),[systemDark,setSystemDark]=useState(()=>matchMedia('(prefers-color-scheme: dark)').matches),[simulation,setSimulation]=useState('real');
  const [prefs,setPrefs]=useState(loadPreferences),[scene,setScene]=useState('charging'),[tab,setTab]=useState('live'),[open,setOpen]=useState(true),[modal,setModal]=useState(null),[settingsTab,setSettingsTab]=useState('appearance');
  const [period,setPeriod]=useState(15),[series,setSeries]=useState(['input','battery']),[point,setPoint]=useState(null),[cleared,setCleared]=useState(false),[notice,setNotice]=useState(''),[storageError,setStorageError]=useState(false);
  const returnFocus=useRef(null);
  useEffect(()=>{if(!modal&&returnFocus.current?.isConnected)returnFocus.current.focus();},[modal]);
  const launcher=useRef(null),scenario=scenarios[scene],theme=resolveAppearance(appearance,simulation==='real'?systemDark:simulation==='dark');
  const rows=useMemo(()=>makeHistory(scenario,period),[scenario,period]),miniRows=useMemo(()=>makeHistory(scenario,15),[scenario]);
  const available=prefs.record&&!cleared;
  useEffect(()=>{const media=matchMedia('(prefers-color-scheme: dark)');const update=e=>setSystemDark(e.matches);media.addEventListener('change',update);return()=>media.removeEventListener('change',update);},[]);
  useEffect(()=>{document.documentElement.dataset.theme=theme;document.documentElement.style.colorScheme=theme;},[theme]);
  useEffect(()=>{try{localStorage.setItem(appearanceKey,appearance);localStorage.setItem('macpower.preferences.v1',JSON.stringify(prefs));setStorageError(false);}catch{setStorageError(true);}},[appearance,prefs]);
  useEffect(()=>{if(!notice)return;const t=setTimeout(()=>setNotice(''),3500);return()=>clearTimeout(t);},[notice]);
  useEffect(()=>setPoint(null),[scene,period]);
  useEffect(()=>{const key=e=>{if(e.key==='Escape'&&!modal){setOpen(false);launcher.current?.focus();}if((e.metaKey||e.ctrlKey)&&e.key===','){e.preventDefault();returnFocus.current=document.activeElement;setSettingsTab('appearance');setModal('settings');}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[modal]);
  const detail=useCallback(key=>setModal(key),[]);
  const updatePref=(key,value)=>setPrefs(p=>({...p,[key]:value}));
  const closeModal=()=>{setModal(null);setOpen(true);};
  const settings=()=>{setSettingsTab('appearance');setModal('settings');};
  const view=next=>{setTab(next);setOpen(true);};
  const changeScene=value=>{setScene(value);setCleared(false);setOpen(true);};
  const exportCsv=()=>{if(!available||scenario.stale){setNotice('当前没有可导出的有效示例记录');return;}const url=URL.createObjectURL(new Blob([historyCsv(rows,scenario)],{type:'text/csv;charset=utf-8;'}));const a=document.createElement('a');a.href=url;a.download=`MacPower-demo-${period}min.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setNotice('已生成示例 CSV，请查看浏览器下载记录');};
  const menuValue=prefs.metric==='percent'?`${scenario.percent}%`:prefs.metric==='input'&&scenario.capacity==null?'未接入':`${watt(scenario[prefs.metric],prefs.metric==='battery')} W`;
  const trendProps={rows,theme,scenario,period,setPeriod,series,setSeries,point,setPoint,available,onExport:exportCsv,onExpand:()=>setModal('history')};
  const tabKeys=['live','trends','health'];
  const tabKey=e=>{if(['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();const next=tabKeys[(tabKeys.indexOf(tab)+(e.key==='ArrowRight'?1:2))%3];setTab(next);document.getElementById(`tab-${next}`)?.focus();}};
  return <main onClickCapture={e=>{if(!modal){const trigger=e.target.closest('button');if(trigger)returnFocus.current=trigger;}}} className="desktop" data-appearance={appearance} data-system-theme={(simulation==='real'?systemDark:simulation==='dark')?'dark':'light'}>
    <header className="menu-bar"><div className="menu-left"><AppleLogo size={18} weight="fill"/><strong>MacPower</strong><span>电源监测</span></div><div className="menu-right"><WifiHigh size={20} weight="bold"/><button ref={launcher} className={`status-item ${open&&!modal?'selected':''}`} aria-label={`MacPower 菜单栏，${metrics[prefs.metric]} ${menuValue}`} aria-expanded={open} onClick={()=>setOpen(!open)}>{scenario.battery>0?<BatteryCharging size={24} weight="fill"/>:<BatteryHigh size={24} weight="fill"/>}<span>{menuValue}</span>{prefs.extra&&prefs.metric!=='percent'&&<span>{scenario.percent}%</span>}</button><span className="menu-date">9 月 23 日 周三</span><time>19:42</time></div></header>
    <div className="desktop-background" onClick={()=>setOpen(false)} aria-hidden="true"/>
    <aside className="preview-controls" aria-label="原型演示控制"><div className="preview-brand"><Logo/><div><strong>MacPower</strong><span>让每一瓦，都有迹可循。</span></div></div><div className="preview-divider"/><p className="eyebrow">交互原型 · 方案 1</p><label>演示场景<select aria-label="演示场景" value={scene} onChange={e=>changeScene(e.target.value)}>{Object.entries(scenarios).map(([key,s])=><option key={key} value={key}>{s.name}</option>)}</select></label><label>模拟系统外观<select aria-label="模拟系统外观" value={simulation} onChange={e=>setSimulation(e.target.value)}><option value="real">使用当前系统</option><option value="light">系统为浅色</option><option value="dark">系统为深色</option></select></label><div className="appearance-status"><span>应用外观</span><strong>{themeLabels[appearance]}{appearance==='system'?` · ${themeLabels[theme]}`:''}</strong></div><button className="preview-settings" onClick={settings}><SlidersHorizontal size={17}/>打开外观设置<ArrowUpRight size={15}/></button><p className="preview-note">所有读数与曲线均为示例。<br/>此原型不会读取设备或修改系统设置。</p><div className="preview-shortcuts"><button onClick={()=>view('live')}>实时</button><button onClick={()=>view('trends')}>趋势</button><button onClick={()=>view('health')}>健康</button></div></aside>
    {open&&<section className={`popover ${modal?'behind-modal':''}`} aria-label="MacPower 电源面板"><div className="popover-header"><div className="app-title"><Logo/><h1>MacPower</h1></div><IconButton label="打开设置" onClick={settings}><GearSix size={23} weight="fill"/></IconButton></div><p className="demo-label">示例数据</p><nav className="tabs" role="tablist" aria-label="电源信息页面">{[['live','实时'],['trends','趋势'],['health','健康']].map(([key,label])=><button key={key} id={`tab-${key}`} role="tab" aria-selected={tab===key} tabIndex={tab===key?0:-1} aria-controls={`panel-${key}`} onKeyDown={tabKey} onClick={()=>setTab(key)}>{label}</button>)}</nav><div className="panel-scroll"><div id={`panel-${tab}`} role="tabpanel" aria-labelledby={`tab-${tab}`}>
    {tab==='live'&&<div className="live-view"><h2 className={`power-status ${scenario.tone}`}>{scenario.tone==='warning'&&<WarningCircle size={17}/>} {scenario.status}</h2><PowerFlow scenario={scenario} theme={theme} onDetail={detail}/><div className="source-caption">{scenario.source}{scenario.stale&&<button onClick={()=>{changeScene('charging');setNotice('已恢复充电示例数据');}} aria-label="重新读取示例"><ArrowClockwise size={14}/></button>}</div><section className="battery-section"><div className="battery-heading"><BatteryHigh size={27}/><strong>电量 <span>{scenario.percent}%</span></strong><span className={`charge-state ${scenario.tone}`}>{scenario.chargingLabel}</span></div><progress aria-label="电池电量" value={scenario.percent} max="100"/><p>{scenario.time}</p></section><section className="mini-trend"><button className="mini-chart-button" onClick={()=>{setPeriod(15);view('trends');}} aria-label="查看电池功率趋势"><h3>电池功率 · 最近 15 分钟</h3>{available&&!scenario.stale?<PowerChart rows={miniRows} theme={theme} compact/>:<div className="mini-empty">{scenario.stale?'等待新的有效读数':'暂无历史记录'}</div>}</button></section><button className="health-summary" onClick={()=>setTab('health')}><Heart size={27}/><span><strong>电池健康</strong><span>100% · 正常</span></span><CaretRight size={19}/></button><footer className="panel-footer"><span>144 次循环</span><button className="text-action" onClick={()=>setTab('trends')}>查看趋势 <ArrowUpRight size={15}/></button></footer></div>}
    {tab==='trends'&&<Trends {...trendProps}/>}
    {tab==='health'&&<section className="health-view"><div className="section-title"><div><h2>电池健康</h2><p>关注长期状态，安心使用。</p></div><Heart size={25}/></div><div className="health-hero"><span className="status-badge"><CheckCircle size={14} weight="fill"/>正常</span><div className="health-number">100<small>%</small></div><span>最大容量 · 系统报告</span><button className="plain-link" onClick={()=>setModal('health-info')}>这与剩余电量有什么区别？<Info size={13}/></button></div><div className="health-details"><div><span>循环次数</span><strong>144 <small>次</small></strong></div>{['电池温度','满充容量','设计容量'].map(label=><div key={label}><span>{label}</span><span className="muted-value">未提供</span></div>)}</div><div className="health-history"><h3>容量变化</h3><div className="health-empty"><ChartLine size={25}/><p>从今天开始，了解电池的变化。</p><span>积累足够记录后可查看趋势。</span></div></div><p className="section-note">循环次数按累计使用电量计算，并非插电次数。</p><button className="text-action" onClick={()=>setModal('system-help')}>查看 macOS 电池设置路径 <ArrowUpRight size={15}/></button></section>}
    </div></div></section>}
    {!open&&!modal&&<button className="reopen-hint" onClick={()=>setOpen(true)}><BatteryCharging size={23}/><span>点击菜单栏，即可查看电力状态</span><ArrowUpRight size={17}/></button>}
    {modal==='settings'&&<Modal title="MacPower 设置" kind="settings-modal" onClose={closeModal}><div className="settings-layout"><nav className="settings-sidebar" aria-label="设置分类">{[['appearance',Sun,'外观与显示'],['record',Database,'数据记录'],['notifications',Bell,'提醒'],['about',Info,'关于']].map(([key,Icon,label])=><button key={key} aria-current={settingsTab===key?'page':undefined} onClick={()=>setSettingsTab(key)}><Icon size={18}/>{label}</button>)}</nav><div className="settings-main">
    {settingsTab==='appearance'&&<><h3>外观</h3><p className="settings-intro">选择熟悉的色彩，让查看更舒适。</p><div className="theme-options" role="radiogroup" aria-label="应用外观">{[['system',CircleHalf],['light',Sun],['dark',Moon]].map(([value,Icon])=><label key={value} className={`theme-option ${appearance===value?'active':''}`}><input type="radio" name="appearance" value={value} checked={appearance===value} onChange={()=>setAppearance(value)} aria-label={themeLabels[value]}/><Icon size={31} weight={value==='system'?'fill':'regular'}/><span>{themeLabels[value]}</span>{appearance===value&&<CheckCircle className="theme-check" size={17} weight="fill"/>}</label>)}</div><p className="theme-explanation" role="status">{appearance==='system'?`当前跟随系统，使用${themeLabels[theme]}外观。系统变化时自动切换。`:`始终使用${themeLabels[appearance]}外观，不受系统外观变化影响。`}</p><h3 className="settings-subheading">菜单栏</h3><label className="setting-row"><span className="setting-label">显示指标</span><select aria-label="菜单栏显示指标" value={prefs.metric} onChange={e=>updatePref('metric',e.target.value)}>{Object.entries(metrics).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><Toggle label="同时显示电量" description="在功率读数旁显示剩余百分比" checked={prefs.extra} onChange={v=>updatePref('extra',v)}/><p className="settings-footnote"><Check size={13}/>{storageError?'此浏览器无法保存设置，仅在当前会话生效':'设置自动保存，即时生效'}</p></>}
    {settingsTab==='record'&&<><h3>数据记录</h3><p className="settings-intro">原型仅保存显示偏好，不采集设备数据。</p><Toggle label="显示示例历史" description="用示例记录体验趋势与导出" checked={prefs.record} onChange={v=>{updatePref('record',v);if(v)setCleared(false);}}/><label className="setting-row"><span className="setting-label">计划保留时长</span><select aria-label="计划保留时长" value={prefs.retention} onChange={e=>updatePref('retention',Number(e.target.value))}>{[7,30,90].map(n=><option key={n} value={n}>{n} 天</option>)}</select></label><div className="data-actions"><button onClick={exportCsv}><DownloadSimple size={17}/>导出示例 CSV</button><button onClick={()=>setModal('clear')}><Trash size={17}/>清空示例历史</button></div><p className="settings-footnote">保留时长仅演示设置。原生版将按所选天数保留本机记录。</p></>}
    {settingsTab==='notifications'&&<><h3>提醒</h3><p className="settings-intro">以下仅演示偏好，不会发送系统通知。</p><Toggle label="低电量提醒" description="电池电量降至 20% 时" checked={prefs.low} onChange={v=>updatePref('low',v)}/><Toggle label="充至指定电量" description="充至 80% 时提醒，不会停止充电" checked={prefs.charged} onChange={v=>updatePref('charged',v)}/><div className="information-note"><Bell size={18}/><p>原生版本会在首次开启提醒时请求通知权限。</p></div></>}
    {settingsTab==='about'&&<><div className="about-brand"><Logo/><h3>MacPower</h3><p>电力，一目了然。</p></div><div className="information-note"><ShieldCheck size={21}/><p>这是可交互的产品设计原型。功率、健康度与历史为示例，未连接真实设备。</p></div><div className="about-links"><a href="https://github.com/exelban/stats" target="_blank" rel="noreferrer">参考：Stats <ArrowUpRight size={14}/></a><a href="https://github.com/lzt1008/powerflow" target="_blank" rel="noreferrer">参考：Powerflow <ArrowUpRight size={14}/></a></div><p className="settings-footnote">图标 Phosphor · 图表 Chart.js · 流向 React Flow</p></>}
    </div></div></Modal>}
    {modal==='history'&&<Modal title="功率趋势" kind="history-modal" onClose={closeModal}><Trends {...trendProps} expanded/></Modal>}
    {modal==='clear'&&<Modal title="清空示例历史？" kind="small-modal" onClose={closeModal}><p>只清空当前演示的历史视图，不影响设备，也不会删除真实文件。切换演示场景即可恢复。</p><div className="dialog-actions"><button onClick={()=>setModal('settings')}>取消</button><button className="primary-button" onClick={()=>{setCleared(true);setModal(null);setTab('trends');setNotice('示例历史已清空，切换场景可恢复');}}>清空示例历史</button></div></Modal>}
    {['input','system','battery','adapter','health-info','system-help'].includes(modal)&&<Modal title={{input:'电源输入',system:'整机耗电',battery:'电池净功率',adapter:'供电能力','health-info':'读懂电池健康','system-help':'macOS 电池设置'}[modal]} kind="small-modal" onClose={closeModal}>
    {['input','system','battery'].includes(modal)&&<><div className="detail-value">{watt(scenario[modal],modal==='battery')} <small>W</small></div><p>{modal==='input'?'当前进入 Mac 的直流功率。它与充电器的供电能力不同，也不等于墙上插座的交流耗电。':modal==='system'?'Mac 当前运行所消耗的功率。优先显示设备遥测；缺少可靠读数时显示估算或留空。':'正值表示电力充入电池，负值表示电池正在供电。功率接近零时，电池几乎没有充放电。'}</p><div className="detail-source"><span>数据类型</span><strong>示例 · {scenario[modal]==null?'暂未提供':(modal==='system'&&scenario.estimated)||(modal==='battery'&&scenario.estimatedBattery)?'估算':'设备遥测口径'}</strong></div></>}
    {modal==='adapter'&&<><div className="detail-value">{scenario.capacity??'—'} <small>W</small></div><p>系统报告的当前连接供电能力，不代表此刻真的输入了这么多功率。</p><div className="detail-source"><span>当前电源输入</span><strong>{watt(scenario.input)} W</strong></div><p className="section-note">连接多个供电端口时，不将它们的功率相加。</p></>}
    {modal==='health-info'&&<><p><strong>剩余电量 {scenario.percent}%</strong>：这次充电后，目前还剩多少电。</p><p><strong>最大容量 100%</strong>：系统报告的电池可储存容量，相对新电池容量的比例。</p><p>健康度不等于剩余寿命，也不意味着电池完全没有老化。循环次数应结合系统状况一起查看。</p></>}
    {modal==='system-help'&&<><p>打开 macOS「系统设置」→「电池」，查看系统提供的电池状况与充电设置。</p><div className="information-note"><Desktop size={20}/><p>网页原型不会跳转或修改系统设置。</p></div></>}
    </Modal>}
    {notice&&<div className="toast" role="status"><CheckCircle size={18}/>{notice}</div>}
  </main>;
}
